version: '3'
services:
  db:
    build:
      context: ./
      dockerfile: ./docker/postgresql
    ports:
      - 5432:5432
    container_name: db_exposed
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --no-locale"
      TZ: Asia/Tokyo
    volumes:
      - postgre_exposed_data:/var/lib/postgresql/data
volumes:
  postgre_exposed_data:
